name: ZHGXTV

on:
  schedule:
    - cron: '0 21,9 * * *'
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    #runs-on: ubuntu-22.04@20240422.1.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.3'

      - name: Install dependencies
        #run: pip install selenium==4.19.0 requests==2.31.0 futures==3.0.5 eventlet==0.36.1
        run: pip install selenium requests futures eventlet aiohttp aiofiles

      #- name: Run itv_all
        #run: python ${{ github.workspace }}/itv_all.py

      - name: Run cctv
        run: python ${{ github.workspace }}/ZHGXTV.py

      - name: Add Custom Channels
        run: |
          cat szdf.txt >> ZHGXTV.txt  # 追加多个直播源
        
      #- name: Run weishi
        #run: python ${{ github.workspace }}/weishi.py
           
      - name: 提交更改
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit *.txt -m "Add generated file"
          git commit *.m3u -m "Add generated file"
          #git pull --rebase
          git push -f
